package com.arv.app.core.model

/** Role inside a family. Enforced again in Firestore rules. The client copy is for UI only. */
enum class MemberRole { OWNER, KEEPER, CONTRIBUTOR, VIEWER }

enum class StoryKind { AUDIO, PHOTO_SET, DOCUMENT, COLLECTION, UPDATE }

/**
 * The four archives a family carries forward. Every memory belongs to exactly one.
 *
 * This is not a tag. It changes who controls the record and what a librarian may do with
 * it, which is why it is an enum on the object rather than a string in a list.
 */
enum class ArchiveArea {
    /** Relationships, names, dates, migrations, places, branches. */
    LINEAGE,

    /** Language, recipes, songs, traditions, faith, celebrations, community. */
    CULTURE,

    /** Voices, photographs, documents, memories, lived experience. */
    STORIES,

    /**
     * Recurring conditions, causes of death, allergies, and other health information a
     * relative deliberately contributed.
     *
     * Health is structurally different from the other three. A record like "her mother
     * had early-onset dementia" is simultaneously one person's private medical history
     * and another person's risk information, which is exactly why families lose it. So
     * control follows the person the record is ABOUT, not the relative who typed it in,
     * and a librarian may never reason across these records. See [MemoryAccess] and
     * [com.arv.app.core.ai.ClinicalClaimGuard].
     */
    HEALTH
}

enum class AssetType { AUDIO, IMAGE, DOCUMENT }

/**
 * How much we actually know about when something happened.
 *
 * UNKNOWN is a legitimate, common answer. Forcing a precise date is how archives end up
 * holding confident lies, so the model carries the uncertainty instead of hiding it.
 */
enum class EraPrecision { EXACT, RANGE, UNKNOWN }

/**
 * Who can see a memory. Set by whoever created it, never widened by anyone else.
 *
 * SELECTED and BRANCH exist because a family is not one flat audience. A story you would
 * tell your sister is not always a story you would tell forty relatives at a reunion.
 */
enum class Visibility { PRIVATE, SELECTED, BRANCH, FAMILY }

/**
 * What a librarian is allowed to do with a memory. Separate from [Visibility] on purpose:
 * "my cousins may read this" and "a model may summarize this" are different permissions,
 * and conflating them is how people get surprised by their own archive.
 */
enum class AiUsePolicy {
    /** Never surfaced by a librarian. Retrievable only by opening it directly. */
    NONE,

    /** May be found and cited, but only quoted verbatim. No paraphrase. */
    QUOTE_ONLY,

    /** May be summarized and woven into an answer. */
    SUMMARY_OK
}

/**
 * Where the content came from. This is the line the product must never blur.
 *
 * Restoring and organizing an authentic recording is preservation. Generating words a
 * person never said and presenting them as that person is fabrication, and in a tool built
 * for grief it is the most harmful thing the software could do. Every surface that renders
 * a memory, including the Memory Garden, reads this field and labels it.
 */
enum class Provenance {
    /** The person's actual voice. */
    AUTHENTIC_RECORDING,

    /** Their handwriting, their photograph, their document. */
    AUTHENTIC_DOCUMENT,

    /** A living relative wrote this themselves. */
    HUMAN_WRITTEN,

    /** Machine transcript or machine tagging of authentic source material. */
    AI_TRANSCRIBED,

    /** Machine-written connective text. Always visibly labeled, never attributed to a person. */
    AI_ORGANIZED
}

enum class UploadState { LOCAL_ONLY, UPLOADING, SYNCED, FAILED }

enum class TranscriptStatus { NONE, PENDING, RUNNING, READY, FAILED }

enum class OutboxOp { CREATE, UPDATE, DELETE, UPLOAD }

enum class PromptOrigin { LIBRARY, GAP_DETECTED, USER }

enum class PromptStatus { SUGGESTED, SAVED, ANSWERED, SKIPPED }

/** A living profile becomes a memorial without losing anything the person chose. */
enum class ProfileState { LIVING, MEMORIAL }

/**
 * How much anybody actually knows that this person is who the record says they are.
 *
 * Genealogy is where families most often store confident lies. A name copied from someone
 * else's tree, or generated by a model, reads exactly like a name taken off a death
 * certificate once both are sitting in the same list, and after one generation nobody
 * remembers which was which.
 *
 * So the archive refuses to flatten them. An unverified ancestor is kept, shown, and
 * plainly labelled as unverified, which turns the shakiest part of a family's record into
 * the part with something to do about it: a list of people somebody could go and confirm.
 */
enum class Confidence {
    /** Someone in the family says so from their own knowledge. */
    FAMILY_TOLD,

    /** Backed by a document: an obituary, a certificate, a census page. */
    DOCUMENTED,

    /** Believed, with a document that only partly covers it. */
    PARTLY_DOCUMENTED,

    /** Written down from research nobody has checked against a record yet. */
    UNVERIFIED,

    /** Unverified, and the sources available disagree with each other. */
    CONFLICTED
}

enum class RelationshipKind {
    PARENT, CHILD, SIBLING, SPOUSE, PARTNER,
    GRANDPARENT, GRANDCHILD, AUNT_UNCLE, NIECE_NEPHEW, COUSIN, CHOSEN, OTHER
}

/** Which archive a librarian question is being asked against. */
enum class LibrarianScope {
    /** Everything this user owns, including their private memories. */
    PERSONAL,

    /** Only what family members deliberately shared. */
    FAMILY
}

/**
 * A person in the family.
 *
 * Not the same thing as an account. A great-grandmother has a profile and no login; a
 * six-year-old has neither. [linkedUserId] is what connects a profile to a real member.
 */
data class Person(
    val personId: String,
    val displayName: String,
    val alsoKnownAs: List<String> = emptyList(),
    val birthYear: Int? = null,
    val deathYear: Int? = null,
    val birthPlace: String? = null,
    val relationLabel: String? = null,
    val linkedUserId: String? = null,
    val state: ProfileState = ProfileState.LIVING,
    /**
     * Who maintains this profile once the person no longer can. Named by the person
     * themselves while they are living, wherever possible.
     */
    val memoryStewardUserId: String? = null,
    val consentGranted: Boolean = false,
    val postMortemOk: Boolean = false,
    /** The later end of a death nobody can date exactly. Null when [deathYear] is exact. */
    val deathYearEnd: Int? = null,
    /** What the record says, in the words of whoever wrote it down. */
    val note: String? = null,
    val confidence: Confidence = Confidence.FAMILY_TOLD,
    val source: String? = null,
    val verifiedAt: Long? = null
) {
    val isDeceased: Boolean get() = deathYear != null || state == ProfileState.MEMORIAL

    /**
     * True when what the archive holds about this person came from published record.
     *
     * Nobody's permission is needed for it, and asking for one would be theatre. An
     * obituary is published, a census page is public, a death record is a matter of record,
     * and the person they describe cannot be asked. A family keeping the facts of their own
     * dead from sources anyone could look up is not doing anything that requires consent.
     *
     * This covers FACTS, which is all a Person is: names, dates, places, who was whose
     * child. It says nothing about memories. A recording of somebody's voice is not public
     * because their obituary was, and that judgement belongs to [Story], not here.
     */
    val isPublicRecord: Boolean
        get() = isDeceased &&
            source != null &&
            (confidence == Confidence.DOCUMENTED || confidence == Confidence.PARTLY_DOCUMENTED)

    /**
     * True when the archive is holding this person on somebody's say-so and has not been
     * told whether they would have minded.
     *
     * Deliberately false for anyone on public record, so the people list stops asking for a
     * consent that neither exists nor is needed.
     */
    val needsAConsentDecision: Boolean
        get() = when {
            isPublicRecord -> false
            // A living yes survives death, and postMortemOk records the decision a
            // family made on a dead person's behalf. This flag was stored and displayed
            // and never actually read, so recording the decision changed nothing.
            isDeceased -> !consentGranted && !postMortemOk
            else -> !consentGranted
        }
}

/** An edge in the family tree. Stored once, rendered from both directions. */
data class Relationship(
    val fromPersonId: String,
    val toPersonId: String,
    val kind: RelationshipKind,
    /** Marked by a keeper when a link is disputed, rather than deleting it. */
    val uncertain: Boolean = false
)

data class Story(
    val storyId: String,
    /**
     * Which family's archive this belongs to.
     *
     * Carried on the object rather than left to the query that fetched it. The boundary
     * used to exist only as a WHERE clause, which meant that once a row had been mapped to
     * a domain type every permission check in the app had already been satisfied.
     */
    val familyId: String = "",
    val title: String,
    val kind: StoryKind,
    val area: ArchiveArea = ArchiveArea.STORIES,
    val narratorIds: List<String> = emptyList(),
    /**
     * Who this record is ABOUT, as opposed to who created it.
     *
     * For most memories this is the same as the narrator. For [ArchiveArea.HEALTH] it is
     * the person whose body the record describes, and it is the field that decides who
     * controls the record.
     */
    val subjectPersonIds: List<String> = emptyList(),
    val eraStart: Int? = null,
    val eraEnd: Int? = null,
    val eraPrecision: EraPrecision = EraPrecision.UNKNOWN,
    val placeLabel: String? = null,
    val tags: List<String> = emptyList(),
    val visibility: Visibility = Visibility.FAMILY,
    val aiUsePolicy: AiUsePolicy = AiUsePolicy.SUMMARY_OK,
    val provenance: Provenance = Provenance.AUTHENTIC_RECORDING,
    /** Explicitly named people, used when visibility is SELECTED. */
    val sharedWithUserIds: List<String> = emptyList(),
    val restricted: Boolean = false,
    /** For BRANCH visibility: the ancestor whose line this belongs to. */
    val branchRootPersonId: String? = null,
    val durationMs: Long = 0L,
    val assetCount: Int = 0,
    val transcriptStatus: TranscriptStatus = TranscriptStatus.NONE,
    val uploadState: UploadState = UploadState.LOCAL_ONLY,
    val createdBy: String = "",
    val createdAt: Long = 0L
) {
    /** "1958 to 1964", "1953", or "Year unknown". Never a fabricated exact date. */
    val eraLabel: String
        get() = when {
            eraPrecision == EraPrecision.UNKNOWN || eraStart == null -> "Year unknown"
            eraEnd != null && eraEnd != eraStart -> "$eraStart to $eraEnd"
            else -> eraStart.toString()
        }

    /** Which decade bucket this belongs in on the timeline. Null when we genuinely don't know. */
    val decade: Int?
        get() = eraStart?.let { (it / 10) * 10 }

    /** True for anything a person actually said, wrote, or photographed. */
    val isAuthentic: Boolean
        get() = provenance == Provenance.AUTHENTIC_RECORDING ||
            provenance == Provenance.AUTHENTIC_DOCUMENT ||
            provenance == Provenance.HUMAN_WRITTEN

    /**
     * An ordinary update today is archive material in thirty years. That is the whole
     * reason a feed belongs inside a preservation tool, so nothing here is second-class.
     */
    val isEverydayUpdate: Boolean get() = kind == StoryKind.UPDATE
}

data class TranscriptSegment(
    val id: Long = 0L,
    val assetId: String,
    val startMs: Long,
    val endMs: Long,
    val text: String,
    val confidence: Float = 0f,
    /** True once a human corrected this line. Provenance: machine versus verified. */
    val humanVerified: Boolean = false
)

data class Prompt(
    val promptId: String,
    val text: String,
    val category: String,
    val targetPersonId: String? = null,
    val origin: PromptOrigin = PromptOrigin.LIBRARY,
    /** Why the app is asking this now. Shown to the user, never a black box. */
    val rationale: String? = null,
    val status: PromptStatus = PromptStatus.SUGGESTED
)

/**
 * One answer from a librarian.
 *
 * [sources] is not decoration. An answer with no sources must not render, because the
 * difference between "Grandpa said this" and "a model wrote this" is the entire
 * trustworthiness of the archive.
 */
data class LibrarianAnswer(
    val question: String,
    val scope: LibrarianScope,
    val text: String,
    val sources: List<LibrarianSource>,
    /** Memories that matched but were withheld by permission. Counted, never named. */
    val withheldCount: Int = 0,
    /**
     * Names of the hive shelves the answer came through, in nomination order. Empty when
     * a flat librarian answered. Shown to the user: retrieval that cannot explain itself
     * has no place in an archive built on provenance.
     */
    val routedThrough: List<String> = emptyList(),
    /** Set by the clinical guard. Drives the disclosure the UI must render. */
    val medicalRecordsPresent: Boolean = false
) {
    val isGrounded: Boolean get() = sources.isNotEmpty()
}

data class LibrarianSource(
    val storyId: String,
    val personId: String?,
    val quote: String,
    val startMs: Long?,
    val provenance: Provenance,
    val area: ArchiveArea = ArchiveArea.STORIES
)
